version: '3.8'

services:
  ebb-platform:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT:-8001}:8001"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s